name: CI - PR Develop

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Docker compose build
        run: docker-compose -f docker-compose.yml build

      - name: Start services with Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: ./docker-compose.yml

      - name: run linter
        run: |
          docker-compose -f docker-compose.yml run --rm auth npm run lint
          docker-compose -f docker-compose.yml run --rm client-gateway npm run lint
          docker-compose -f docker-compose.yml run --rm orders npm run lint
          docker-compose -f docker-compose.yml run --rm payments npm run lint
          docker-compose -f docker-compose.yml run --rm products npm run lint
